project:
  type: book
  output-dir: docs

book:
  title: "LearningDiary"
  author: "Yao Wang"
  date: "2023/1/30"
  chapters:
    - index.qmd
    - Summary.qmd
    - Gettingstartedwithremotesensing.qmd
    - Portfolio.qmd
    - Corrections.qmd
    - Policy.qmd
    - GoogleEarthEngine.qmd
    - Classification1.qmd
    - Classification2.qmd
    - Temperature.qmd
    - references.qmd
    

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

